### ISSUE TITLE
Subscription fails sometimes

### ISSUE THREAD

**Issue by sungodavi** [Surnet/graphql-amqp-subscriptions#10]
<img width="1042" alt="Screen Shot 2020-04-26 at 10 52 54 AM" src="https://user-images.githubusercontent.com/17483090/80312677-16828a80-87ac-11ea-8ade-e66c7c308dc9.png">

I have an integration test case that listens to a subscription and then immediately makes a mutation, which then publishes a message. Every once in a while, I receive the error above, which prevents the subscription from being sent and then fails the test case. Other times I receive this error:

<img width="1090" alt="Screen Shot 2020-04-26 at 10 58 10 AM" src="https://user-images.githubusercontent.com/17483090/80312787-f7d0c380-87ac-11ea-99da-640479040146.png">

This doesn't fail the test case, but I'm still wondering what the issue is. Any ideas?

My test code:

test.js
```
it(`complete the expert action`, () => {
      const subscriptionQuery = `
        subscription {
          completedExpertAction {
            expertAction {
              id
            }
          }
        }
      `;
      const query = `
        mutation f($form: JSON) {
          completeExpertAction(expertActionId: "${currActionId}", response: $form)
        }
      `;

      const variables = {
        form: expertActionResponse
      };
      const subscriptionPromise = subscriber.getNextSubscription(subscriptionQuery);

      return request.post('/graphql')
        .send({ query, variables })
        .expect(200)
        .then(res => {
          assert.isTrue(res.body.data.completeExpertAction);
          return subscriptionPromise;
        })
        .then(result => {
          assert.equal(result.completedExpertAction.expertAction.id, currActionId);
        });
    });
```

utils.js
```
function createSubscriber(authToken) {
  const wsClient = new SubscriptionClient(`ws://${process.env.GRAPHQL_HOST}:${process.env.PORT}/graphql`, {
    reconnect: true,
    connectionParams: {
      authToken
    }
  }, ws);
  const wsLink = new WebSocketLink(wsClient);
  const apollo = new ApolloClient({
    link: wsLink,
    cache: new InMemoryCache({ addTypename: false })
  });
  return {
    close() {
      wsClient.close();
    },
    getNextSubscription(query) {
      return new Promise((resolve, reject) => {
        apollo.subscribe({
          query: gql`${query}`
        }).subscribe({
          next: ({ data }) => resolve(data),
          error: reject
        });
      });
    },
    apollo
  };
}
```

**Comment by jacobcabantomski-ct** [comment]
@sungodavi We've been running into this issue as well, after digging around have determined it is a race condition when an unsubscribe is running for the last sub for a routing key and a new subscription for that same routing key comes in.

1. Unsubscribe comes in. It is the last subscription so the consumer is disposed https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L119
2. While the disposer is running, a new sub comes in with the same key and is added to sub refs: https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L58-L59
3. Disposal finishes and all subs for that routing key including the new one) are deleted https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L120
4. Unsubscribe comes in, sub has already been removed, error is thrown.

Pre step 4, this means the new sub will never get any updates.

I'm currently working on a fix but may not have time to properly finish it until early next week. I'll make sure to post where I get with that in here.

**Comment by jacobcabantomski-ct** [comment]
@sungodavi If you need a fix before https://github.com/Surnet/graphql-amqp-subscriptions/pull/11 is merged and tagged, see https://github.com/Surnet/graphql-amqp-subscriptions/pull/11#issuecomment-623807758

**Comment by chdanielmueller** [comment]
This works better as before.
I will publish this version as 1.0.7

But it still fails on my machine if I don't add a console.log anywhere.
Which for me means that there still is a race condition.

`(node:32897) UnhandledPromiseRejectionWarning: AssertionError: expected [TypeError: Cannot read property 'routingKey' of undefined] to not exist
    at /Users/chdanielmueller/Documents/Repositories/graphql-amqp-subscriptions/src/pubsub.test.ts:162:25
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:32897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) should be able to receive a message after one of two subscribers unsubscribed (concurrent)`

`1) AMQP PubSub
       should be able to receive a message after one of two subscribers unsubscribed (concurrent):
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/chdanielmueller/Documents/Repositories/graphql-amqp-subscriptions/src/pubsub.test.ts)`

Thanks to @jacobcabantomski-ct for working on this.
If you would like to revisit this it would be awesome.
Unfortunately there is a lot going on on my side so I can not help much at the moment.
But I will make sure to review within a reasonable timeframe.
Please write me an email to daniel.mueller@surnet.ch if there is anything you need help with or there is something ready for review

**Comment by jacobcabantomski-ct** [comment]
# Why that test case is now failing

I discovered the change from my code that is causing that test failure: https://github.com/Surnet/graphql-amqp-subscriptions/commit/527dfbb18729f2554b7af354fa504d2d75d02e14#diff-b8cdf81e4bff3d33bd189372a1b280b8R24-R26

When tests cases were being run for that file, they were bringing in the end state of  previous test runs. For that specific test case, there was already a subscriber from the previous test on the same routing key and so it did not start in an empty state. With my change, it now does and hits a new and exciting race condition! Woohoo!

# The new (hotness) uncovered bug

https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L57-L71

1. https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L62 is hit by sub 1 and waits for a subscription to finish.
2. sub 2 hits the same subscribe call as subRef mapping occurs after the subscribe call is resolved (https://github.com/Surnet/graphql-amqp-subscriptions/blob/master/src/pubsub.ts#L64-L67)
3. sub 1 subscribe resolves
4. sub 2 subscribe resolves, overwriting the subRef data from sub 1. Only sub 2 is registered now. Note this also disposes the first ampq subscription from sub 1.

Will have another PR up shortly to address and switch most things in the codebase over to `async/await`;
