### ISSUE TITLE
Configurable Queue

### ISSUE THREAD

**Issue by mmcasavant** [Surnet/graphql-amqp-subscriptions#15]
First off thank you so much for your efforts I think the project is the best AMQP / RabbitMQ implementation yet. I'm wondering, what would anyone think about making the queue configurable as well as the exchange? I have a few real time apps that both consume from the same topic exchange, I want each app to get a copy each time I pull new data in through a long poll I'm running on an interval. I'm using the updated data in multiple apps so I have to create multiple queues to achieve this... if I consume from the default queue '' then only one of the apps is going to receive the update, correct? I think this is a valid use case that has yet to be accounted for in any implementation. I'm happy to contribute some time myself to adding the configuration of queues. Does my idea sound plausible? I am new to RabbitMQ and this is why I am running the idea by you guys first because perhaps there is a better RabbitMQ implementation that I could write to better integrate into this plugin but I've done a fair amount of poking around in the docs and I'm not sure there is a way to achieve this. Fundamentally when you read from any queue the work is completed when acknowledged so the first app to receive the data is what gets the data update and the other does not.

https://stackoverflow.com/questions/41160585/rabbitmq-same-message-to-each-consumer

I suppose you could bind 2 exchanges each of which would have a default queue and just publish to both from another app? Would this be a misuse of exchanges?

**Comment by chdanielmueller** [comment]
Hi @mmcasavant 

Please take a look at #2.
This could maybe be a solution to your request for config.
I will try to look at this PR in the next few days, but a lot is going on in these times...

As far as the receive from multiple sources this is already handled by the library.
If you subscribe to topic "XY" and on another server/service subscribe to "XY" as well both will get the messages.
They create own exclusive queues which will then be attached to the exchange with the routingKey/topic.
That way you can publish to the exchange with the routingKey/topic and both subscribers will get the message.

Cheers,
Daniel

**Comment by gad0lin** [comment]
Hey, 

 any update on it? Would be great to get PR for config in. 

Cheers,  K

**Comment by chdanielmueller** [comment]
Review is planned for this weekend.
Sorry for keeping you waiting

**Comment by chdanielmueller** [comment]
Released in 1.1.0
