### ISSUE TITLE
Feature Request: Ability to make graphql_subscriptions durable

### ISSUE THREAD

**Issue by sungodavi** [Surnet/graphql-amqp-subscriptions#18]
We would really like to have our GrapQL exchange to be durable. However, durability is hardcoded to be false.

**Comment by chdanielmueller** [comment]
Configuring the settings is coming soon.
There is a pull request containing some things, but I will have to do some other changes first.

I try to allocate some more time to this project since it seems to get a lot of traction at the moment.

**Comment by chdanielmueller** [comment]
Please check blockrange/graphql-amqp-subscriptions#2 as soon as we verify this PR I will merge the config feature
