### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Missing value for mandatory field 'consumerTag'

### ISSUE THREAD

**Issue by Devvicktor** [Surnet/graphql-amqp-subscriptions#29]
I ran into this error when I tried to filter the subscriptions against given variables;
` return withFilter(
      () => subscriber.asyncIterator("NEWCOUNT"),
      (payload, variables) => {
        console.log("PAYLOAD", payload);
        console.log("VARIABLES", variables);
        return payload.liveUpdates.id === variables._id;
      }
    )();`
any idea on this

**Comment by Devvicktor** [comment]
issue resolved

**Comment by EKivutha** [comment]
Issue still exists
