### ISSUE TITLE
Using the pubsub instance

### ISSUE THREAD

**Issue by fetimo** [Surnet/graphql-amqp-subscriptions#4]
Hi,

I'm implementing graphql-amqp-subscriptions 1.0.4 into my app using Apollo Server 2.7.0 and am wondering how you use the `pubsub` instance.

Given this code:

```
const rabbitmqConnection = amqp
  .connect(`amqp://${ user }:${ password }@${ host }:${ port }?heartbeat=30`)
  .catch((error) => {
    console.error('error connecting', error);
  });

export const pubsub = (async (conn) => {
  const connection = await conn;
  return new AMQPPubSub({
    connection,
    exchange
  });
})(rabbitmqConnection);
```

I'm trying to export the pubsub instance to then use it elsewhere in the app (e.g. in resolvers).

However because it is exported as a Promise `withFilter` throws an error (`asyncIterator.next is not a function`):
```
import { withFilter } from 'apollo-server-express';
import { pubsub } from '../pubsub';
[...]
Subscription = {
    create_message: {
      subscribe: withFilter(
        async () => {
          const pub = await pubsub;
          return pub.asyncIterator('CREATE_MESSAGE');
        },
        (payload, variables) => {
          // run filter
        },
      )
    }
  };
```

How do you recommend using the pubsub instance in other areas of your app without wrapping the entire application?

Ideally it'd be great to just do something like the Google PubSub client https://github.com/axelspringer/graphql-google-pubsub#creating-the-google-pubsub-client.

Many thanks!

Edit: I've come up with this naive solution for now. It exposes a limited public interface until the connection is setup and then publishes any queued actions.

```
const queue = [];

// eslint-disable-next-line import/no-mutable-exports
export let pubsub = {
  publish: (key, content) => {
    queue.push({ key, content });
    console.log('🐰 RabbitMQ connection not ready yet');
  },
  asyncIterator: () => console.log('🐰 RabbitMQ connection not ready yet')
};

amqp
  .connect(`amqp://${ user }:${ password }@${ host }:${ port }?heartbeat=30`)
  .then((connection) => {
    pubsub = new AMQPPubSub({
      connection,
      exchange
    });

    console.log('🐰 RabbitMQ ready to hop');
    
    // Go through items queued while waiting
    queue.forEach(({ key, content }) => {
      pubsub.publish(key, content);
    });
    if (queue.length) {
      console.log(`🐰 Processed ${ queue.length } queued messages`);
      queue.length = 0;
    }
  })
  .catch((error) => {
    console.error('🐰 Error connecting to RabbitMQ:', error);
  });
```

**Comment by chdanielmueller** [comment]
I depend on RabbitMQ for all GraphQL requests.

Because of that:
- I wait with starting my Apollo Server until I have a running RabbitMQ connection.
- I also terminate/restart my server as soon as my RabbitMQ connection fails.

I hope this answers your question

**Comment by goodok21** [comment]
@fetimo 
- create connection in async and create `const pubsub = new AMQPPubSub(...)` when your server starts inside async/await function
- pass current `pubsub` into subscription server `context` and use in subscription resolver
