### ISSUE TITLE
Can we update deps ?

### ISSUE THREAD

**Issue by ruscon** [Surnet/graphql-amqp-subscriptions#44]
I can create a PR, if you want.
I need `graphql` ^16

You use `graphql-subscriptions@1.2.1`
Which requires:
```
"peerDependencies": {
  "graphql": "^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0"
},
```

**Comment by chdanielmueller** [comment]
Please try the newest beta
`npm i graphql-amqp-subscriptions@2.0.0`

**Comment by ruscon** [comment]
@chdanielmueller Already. Works for me
