### ISSUE TITLE
AMQP 1.0

### ISSUE THREAD

**Issue by Victordmdb** [Surnet/graphql-amqp-subscriptions#5]
Any recommendations on integrating with AMQP 1.0 broker? `amqplib` doesn't support it.

**Comment by Victordmdb** [comment]
I found https://github.com/amqp/rhea, i'll test to see if its compatible with this lib

**Comment by chdanielmueller** [comment]
@Victordmdb Have you found something?
Out of interest. What are your circumstances that need you to work with a AMQP 1.0 broker?

**Comment by Victordmdb** [comment]
For using with AWS MQ. I switched to `mqtt` and `graphql-mqtt-subscriptions` instead.
